### ISSUE TITLE
Handle pagination on Harbor endpoints dynamically

### ISSUE THREAD

**Issue by steadyk** [steadforce/harbor-day2-operator#2]
Currently the operator has a fixed `page_size` of 100 on requests to Harbor.

To avoid potential issues with responses which could have more pages, we want to implement a dynamic handling of pages on requests to Harbor.

**Comment by peters-david** [comment]
Although not obvious in combination with the pagination parameters, it is possible to fetch all resources of a kind by passing the parameter `limit=None` to the client request according to https://github.com/unioslo/harborapi/pull/26.

The `page_size` variable and parameter was removed in https://github.com/steadforce/harbor-day2-operator/commit/395271998abb28a78a61174fb7b614a8d6b7b366 and instead `limit=None` was added at the respective places. As `None` is the default value for `limit` in resource requests it is not neccessary to set it explicitly, but was set here both for clarity and in case the default value gets changed in future releases of [harborapi](https://github.com/unioslo/harborapi).
