### ISSUE TITLE
Robot V1 API

### ISSUE THREAD

**Issue by steadyk** [steadforce/harbor-day2-operator#28]
Should we switch to the robot v1 API?

See https://unioslo.github.io/harborapi/endpoints/robotv1/

**Comment by peters-david** [comment]
What would be the reason? As far as I can tell everything in the robot v1 API can also be done with the [newer robot API](https://unioslo.github.io/harborapi/endpoints/robots/).

**Comment by steadyk** [comment]
Good point! Looks like the robot v1 API is the older one.

Indicators might be:
* [Harbor robots](https://github.com/goharbor/harbor/blob/e0b94aa7d7277fede3b42add7332d5dc8d5df3f5/src/server/v2.0/handler/robot.go) (Last change 6 months ago)
* [Introduction of robots](https://github.com/goharbor/harbor/commit/8e61a3ea31fc1e9f1ba5fad41abbfd0f0dd6bc95)
* [Harbor robots v1](https://github.com/goharbor/harbor/blob/e0b94aa7d7277fede3b42add7332d5dc8d5df3f5/src/server/v2.0/handler/robotV1.go) (Last change last year)
* [Robot v1 deprecation](https://github.com/goharbor/harbor/pull/15296)

In the Python Harbor library, the robots v1 endpoints might be just added for compatibility with older Harbor versions.
See:
* https://github.com/unioslo/harborapi/issues/87
* https://github.com/unioslo/harborapi/pull/88

I'm not completely sure about the robot endpoints, but I guess it make sense to stick to the already used robots endpoints.

Thanks for the hint and sorry for the noise!
